N: 10
dt: 0.1
num_tvs: 5
a_max: 3.0
a_min: -5.0
v_max: 15.
v_min: -1.
a_lat: 3 #m/s^2 used for lane chance mode prediction of the TVs
eval_mode_category: 0 #0: closed-loop with IDMAgent observation, 1: open-loop (TVs do not react to EV) using logged trajectories 
is_mm_preds: True #If evaluation mode is 0, this should be True. Otherwise, False
save_dir: /home/mpc/nuplan-devkit/nuplan/expert_data/nuplan_expert_data_N10.pkl
l1_lmbd: 100